
name: Java App Service CI/CD

on:
  push:
    branches: [master]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14

      - name: Build project with Maven
        run: mvn clean install --file pom.xml
        
      - name: Dependency Test
        run: mvn dependency:analyze
        
      - name: Run Tests with Code Coverage
        run: mvn test jacoco:report
